// domain.com/all-posts

import { Fragment } from 'react';
import Head from 'next/head';

import BlogList from '../../src/components/Blog/BlogList';

export default function Home(props) {
    return (
        <Fragment>
            <Head>
                <title>All Posts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>All Posts</h1>
                {props.blogPosts &&
                    <BlogList blogPosts={props.blogPosts} />
                }
            </main>
        </Fragment>
    )
};

export const getStaticProps = async () => {
    const response = await fetch('https://open-blog-nextjs-default-rtdb.europe-west1.firebasedatabase.app/blog-posts.json');
    const data = await response.json();
    const blogPosts = [];

    if (data) {
        Object.entries(data).map(post => {
            post[1].id = post[0];
            blogPosts.push(post[1]);
        });
    }

    return {
        props: {
            blogPosts
        },
        revalidate: 10
    }
};