// domain.com/

import { Fragment } from 'react';
import Head from 'next/head';

import LatestPost from '../src/components/Blog/LatestPost';
import BlogList from '../src/components/Blog/BlogList';
import styles from '../styles/HomePage.module.css';

export default function Home(props) {
    return (
        <Fragment>
            <Head>
                <title>Open Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className={styles.title}>Open Blog</h1>
                <h2 className={styles['second-title']}>A blog ran by anyone.</h2>
                {props.blogPosts.length > 0 &&
                    <Fragment>
                        <LatestPost blogPosts={props.blogPosts} />
                        <BlogList blogPosts={props.blogPosts} />
                    </Fragment>
                }
                {props.blogPosts.length === 0 &&
                    <h2>
                        <span>No blog posts yet!</span> 
                        <br />
                        <span>Be the first one to blog about what ever you want!</span>
                    </h2>
                }
            </main>
        </Fragment>
    )
};

export const getStaticProps = async () => {
    const response = await fetch('https://open-blog-nextjs-default-rtdb.europe-west1.firebasedatabase.app/blog-posts.json');
    const data = await response.json();
    const blogPosts = [];

    if (data) {
        Object.entries(data).map(post => {
            post[1].id = post[0];
            blogPosts.push(post[1]);
        });
    }

    return {
        props: {
            blogPosts
        },
        revalidate: 10
    }
};